### ISSUE TITLE
container fails to start 

### ISSUE THREAD

**Issue by hpio** [V3ckt0r/fluentd_exporter#9]
Recent upgrade seems to have broken fluentd_exporter, when using *latest* tag i get the following error when running on Kubernetes 1.9.3:

```
+ exec app -insecure false -log.format "logger:stderr" -log.level "info" -scrape_uri "http://localhost:24220/api/plugins.json" -telemetry.address ":9309" -telemetry.endpoint "/metrics"
/usr/local/bin/go-wrapper: 89: exec: app: not found
```

*kube* version on the other hand throws the following:
```
Error: failed to start container "fluentd-exporter": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "e
xec: \"go-wrapper\": executable file not found in $PATH"
```

container is deployed with the following arguments: 
```
    spec:
      containers:
      - args:
        - run
        - -insecure
        - "false"
        - -log.format
        - '"logger:stderr"'
        - -log.level
        - '"info"'
        - -scrape_uri
        - '"http://localhost:24220/api/plugins.json"'
        - -telemetry.address
        - '":9309"'
        - -telemetry.endpoint
        - '"/metrics"'
        command:
        - go-wrapper
```

**Comment by V3ckt0r** [comment]
Hey @hpio,

Woops sorry about that. I made some changes to the Docker image so the go-wrapper is no longer being used. Try changing your deployment manifest to something like:
```
    spec:
      containers:
      - args:
        - "-scrape_uri=http://localhost:24220/api/plugins.json"
        - "-telemetry.address=:9309"
        - "-telemetry.endpoint=/metrics"
```

Let me know how you get on.

Cheers.
